### ISSUE TITLE
scripts/assault/functions_waves.sqf зомечание

### ISSUE THREAD

**Issue by 10Dozen** [FrozenFrogsMissionworks/mission1994#1]
Не будет работать на дедикейтеде (локального плеера там нет)

https://github.com/Cambusta/mission1994/blob/81efd68942da4380634a7e0990a64ed87df38010/scripts/assault/functions_waves.sqf#L17

Делай getPos ( selectRandom ((call BIS_fnc_listPlayers) select { alive _x }) ) -- возвращает позицию рандомного живого игрока

**Comment by Cambusta** [comment]
Спасибо, заменю.

**Comment by Cambusta** [comment]
Fixed.
